describe('Account management should be usable', function() {
   beforeEach(function () {
      cy.visit('http://localhost:8080/login')
      cy.contains('Login')
      cy.get('#exampleInputEmail1')
      	.type('admin@gmail.com')
      cy.get('#exampleInputPassword1')
         .type('admin')
      cy.get('.btn')
         .click()
      cy.wait(1000)
      cy.visit('http://localhost:8080/accounts')
   })

   it('Should have accounts', function() {
		cy.contains('Admin/Employee Management')
		cy.get('table > :nth-child(2) > :nth-child(2)')
			.contains('Admin User')
		cy.get('table > :nth-child(2) > :nth-child(4)')
			.contains('true')
		cy.get('table > :nth-child(3) > :nth-child(2)')
			.contains('Employee User')
		cy.get('table > :nth-child(3) > :nth-child(4)')
			.contains('false')
   })

   it('Should allow account creation/modification', function() {
		cy.contains('Admin/Employee Management')
		cy.get('.create-account')
			.click()
		cy.get('[type="text"]')
			.type('Test User')
		cy.get('[type="email"]')
			.type('test@gmail.com')
		cy.get('[type="password"]')
			.type('test')
		cy.get('.signupbtn')
			.click()
		cy.wait(1000)
		cy.get('table > :nth-child(4) > :nth-child(2)')
			.contains('Test User')
		cy.get(':nth-child(4) > :nth-child(5) > .remove')
			.click()
		cy.wait(1000)
		cy.get('table > :nth-child(4) > :nth-child(2)').should('not.exist')
   })
})
